# Generated by Django 4.2 on 2023-12-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
